- name: customer version profile
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Gather information about all customer version profile
      willguibr.zpacloud.zpa_customer_version_profile_info:
        name: "New Release"
        # id: 216196257331282234
      register: data
      
    - debug: 
        msg: "{{ data }}"